name: Deploy EKS Cluster

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: envs/prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: envs/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: envs/prod
