name: Terraform Simple

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      action:
        description: "apply or destroy"
        required: true
        default: apply

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: envs/prod

      # ✅ PLAN (only on push)
      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan
        working-directory: envs/prod

      # ✅ APPLY (manual only)
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve
        working-directory: envs/prod

      # 💣 DESTROY (manual only)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: envs/prod
